spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081