### Create Customer
POST http://localhost:8081/customers
Content-Type: application/json

{
  "name": "Rahul",
  "email": "rahul.accounts@gmail.com",
  "phone": "9876543210",
  "address": {
    "city": "Hyderabad",
    "state": "Telangana"
  },
  "accounts": [
    {
      "accountNumber": "ACC1001",
      "balance": 5000
    },
    {
      "accountNumber": "ACC1002",
      "balance": 12000
    }
  ]
}

###

### Get All Customers
GET http://localhost:8081/customers

###

### Get Customer By Id
GET http://localhost:8081/customers/12

###

### Update Customer
PUT http://localhost:8081/customers/6
Content-Type: application/json

{
  "name": "Rahul Sharma",
  "email": "rahulsharma@gmail.com",
  "phone": "8888888888"
}

###

### Delete Customer
DELETE http://localhost:8081/customers/6

###

### Customer Not Found
GET http://localhost:8081/customers/100

